name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a mapper with...
        2. Execute with data...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      placeholder: |
        ```typescript
        import { Mapper } from 'om-data-mapper';
        
        // Your code here
        ```
      render: typescript
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Message / Stack Trace
      description: If applicable, paste the error message or stack trace
      placeholder: Paste error message here...
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: om-data-mapper Version
      description: What version of om-data-mapper are you using?
      placeholder: e.g., 2.0.5
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 20.9.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running the code?
      options:
        - Node.js
        - Browser
        - Both
        - Other
    validations:
      required: true

  - type: dropdown
    id: typescript
    attributes:
      label: TypeScript
      description: Are you using TypeScript?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: input
    id: typescript-version
    attributes:
      label: TypeScript Version (if applicable)
      description: What version of TypeScript are you using?
      placeholder: e.g., 5.3.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a minimal code sample that reproduces the issue
          required: false
        - label: I am using the latest version of om-data-mapper
          required: false

